fabricante:
    resource: "@FabricanteBundle/Resources/config/routing.yml"
    prefix:   /

personal:
    resource: "@PersonalBundle/Resources/config/routing.yml"
    prefix:   /

cliente:
    resource: "@ClienteBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
